import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "../styles/globals.css";

const notoSansThai = Noto_Sans_Thai({
  subsets:["latin", "thai"],
  weight: ["100", "300", "400", "500", "700"],
  variable: "--font-noto-sans-thai",
  display: "swap",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={`${notoSansThai.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
